### ISSUE TITLE
[Error] Deprecated octokit.authentication() function

### ISSUE THREAD

**Issue by clifford-lc** [adamzolyak/monorepo-pr-labeler-action#2]
FYI it seems the authenticate() function in octokit has been deprecated since your last release, producing the following non-breaking error. 

```
Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/action/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:4:26)
    at Object.<anonymous> (/action/app.js:11:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
labeling repo: packages
```

**Comment by adamzolyak** [comment]
👍 looking into it.

**Comment by mrcasals** [comment]
Also reported in https://github.com/waffleio/waffleio-gh-actions/issues/18 :smile:
